### ISSUE TITLE
Focusing of "Reworking off-topic closure policies" and why effort is generally a bad metric

### ISSUE THREAD

**Issue by berquist** [GaurangTandon/ReworkingClosurePoliciesChemSE#1]
In my opinion, there is still not enough focus here. The reason is we have years of meta discussion and chat logs about this, with different levels of discoverability and focus themselves, and we could read them all and not be done until the heat death of the universe, just in order to contextualize any future discussion. That sentence above is already too long.

To me, tackling the whole problem at once is difficult, and combined with the contextualization issue above results in something like a pull request that's too large to review properly. Because all parts of the problem are connected, it's like a choose-your-own-adventure book, where initial decisions dictate and restrict later ones. Most time in this doc is spent on effort, [so let's talk about effort.](https://chemistry.meta.stackexchange.com/q/3807) I wonder if you're missing the point in your comments on that post. It sounds like you agree with [this answer](https://chemistry.meta.stackexchange.com/a/3816), but then it gets so long I can't follow you and doesn't seem relevant. Missing the point then carries over to this document; under your statement for problem 1,

> As for the actual close reason, it should be called "low-effort".

This is still not enough. You reference [an answer that discusses this](https://chemistry.meta.stackexchange.com/a/3722).

1. The double standard of high-rep users with low-effort questions.
2. The level of problem difficulty.
3. The definition of "problem difficulty".

I will illustrate this with an example question that doesn't appear on the site.

> How does the Tamm-Dancoff approximation (TDA, identical to the CIS approximation) fix the "triplet instability problem" present in the random phase approximation (RPA, identical to TDHF)?

With a few hours, I could come up with a written answer for the above. A graduate student in theoretical chemistry should be able to figure it out, probably by hand, but at least from references. I don't know if it's in a popular book, but it's certainly in the peer-reviewed literature. It's difficult from a high school and college perspective because it's gibberish, _maybe_ from a first-year graduate student level because you're still learning about quantum mechanics and quantum chemistry, but really only because you need to progress through your studies to understand the question's language. It isn't _intrinsically_ very difficult, like an open research question. It has a concrete answer. Is it a good question from a conceptual point of view? I think so, but can definitely see how it also isn't. Is it low effort? Yes. I can make it appear to be even lower effort:

> How does the Tamm-Dancoff approximation fix the "triplet instability problem" present in the random phase approximation?

See what I did there? Rewind slightly. Under "What effort do I need to do before asking a question?",

> But why do you want me to show effort in the first place? That is primarily because of the reason that we want to help _you_, not the person who set your textbook questions.

If you agree with the view that questions and answers are for collective knowledge (many of Martin's comments, [here](https://chemistry.meta.stackexchange.com/a/4247)), and the benefit to the asker is merely a side effect, then this argument is invalidated. All of this can go out the window if you decide on the minimum barrier for content difficulty. Is it American high school? University/college/undergraduate? Masters? PhD? [This was asked at the inception of the site.](https://chemistry.meta.stackexchange.com/questions/41/what-kind-of-subjects-in-chemistry-are-considered-too-easy) My point 3 is too fine-grained, so it's sufficient to say the definition of difficulty refers to having up to that level of vocabulary, or the topic is covered in a textbook at that level. Language like

> If you're asking a more advanced question which concerns current research, look for relevant papers, including checking on arXiv.

is dangerous, because the people who don't know to do this may not be able to understand the material, or may not have access (for paywalled journals), and for people who do know, it may be outside their field, among other reasons. Some of this can be deduced from our discussion about [encouraging better questions](https://chemistry.meta.stackexchange.com/q/3813). Should I ask that question on the site, even though I can look for relevant papers? Maybe yes, but then, should I think about self-answering it and every other question I ask on the site?

I agree with your points, but I think that if you focus more on the difficulty (but not entirely), rather than effort, it will help. This is the part that is my opinion, and is the most up for debate. Most vampire questions are mid-undergraduate level or lower. Not allowing questions at that level would get rid of vampires and equivalent thought experiments. Then the criteria for new CV reasons is changed, because those questions aren't closed, they're straight-up deleted. Overall, I still think your docs put us in a better position. The few of us with the non-effort criteria are certainly unpopular with those who just want their question answered, and the people who are ok with the current system, and I don't know how to handle that.

**Comment by polyluxus** [comment]
I think *effort* is the worst possible metric you could pick for a custom close reason.

You cannot quantify effort in a meaningful way; you even cannot say whether a lot of effort is good, and little is bad, or the other way around. It simply is no objective metric and therefore always open for debate, and eventually liable to interpretation by the individual acting in the queues or on the posts. In my opinion this is the biggest problem with the current close reason.

The lines become blurred again: what is enough effort, and how would we verify that the effort given was enough. While we certainly can all agree that copy and pasted questions are bad in all metrics, effort becomes increasingly difficult to judge on questions that fall into the grey areas. In the end, we'll probably switch one boilerplate reason for another. Or at least this is probably going to be the way they are treated.

Don't get me wrong; there is still lots of good points raised here, and they need to be dealt with, but I think the key problem won't get fixed with being more descriptive about *effort*. It will especially not fix [problem 3](https://github.com/GaurangTandon/ReworkingClosurePoliciesChemSE/blob/master/Reworking%20off-topic%20closure%20policies.md#problem-3-the-homework-policy-wasis-often-used-as-a-dump-for-i-dont-like-this-questiontoo-basic-lets-vtc). 

I think we should go a different route:  
A question should be conceptual, it should after it being answered be applicable to similar situations, and therefore be more helpful in the long run. Effort should be a judgement call, whether you up-/down-vote or not.   
Obviously, a copy and pasted question will not identify the concept, and the problem the OP has with it, so we're getting rid of those, which is probably the most important thing for the regular voters.

I regularly down-vote questions with low effort, or  missing context/ perspective/ re-usability; I don't want to close them. Consider the example question from Marko, [which was mentioned here](https://github.com/GaurangTandon/ReworkingClosurePoliciesChemSE/blob/master/Reworking%20off-topic%20closure%20policies.md#short-questions-and-low-effort-questions-correlation-but-not-a-causality); I down-voted that one, because I find it incredibly lazy and it doesn't even try to identify the conceptual issue he might have had. I bet ron took more time drawing that image than actually thinking about the answer - the solution is *that* obvious. (Btw. most questions of Marko are of this quality.) And even though I find the question terrible, it is a useful one because of ron's answer. Based on effort, this should have been nailed shut immediately.

---

I think that many of the active voters don't really consider all the consequences. That really is something that should be changed, but it won't be with any new policy. The essential point is that **with a close-vote you are saying: this does not belong here.** The final consequence should in those cases be deletion. In my opinion, we retain too many closed questions, and while we do that, the whole quality control motivation is void. But that is a discussion for another day...

**Comment by GaurangTandon** [comment]
> If you agree with the view that questions and answers are for collective knowledge, and the benefit to the asker is merely a side effect, then this argument is invalidated. 

> You cannot quantify effort in a meaningful way; you even cannot say whether a lot of effort is good, and little is bad, or the other way around. It simply is no objective metric and therefore always open for debate, and eventually liable to interpretation by the individual acting in the queues or on the posts. In my opinion this is the biggest problem with the current close reason.

> A question should be conceptual, it should after it being answered be applicable to similar situations, and therefore be more helpful in the long run. Effort should be a judgement call, whether you up-/down-vote or not. Obviously, a copy and pasted question will not identify the concept, and the problem the OP has with it, so we're getting rid of those, which is probably the most important thing for the regular voters.

Thank you all for your valuable points. I have changed my mind over the time since I wrote this repo and I agree with you both that "effort" is the worst metric to fix our current problem. I will start by reviving the [RFCP](https://chemistry.meta.stackexchange.com/questions/3698/canonical-qa-proposing-a-patronage-system/3700#3700) initiative.
